la-mia-pizzeria-static/Models/Pizza.cs
using System.ComponentModel.DataAnnotations;

namespace la_mia_pizzeria_static.Models
{
    public class Pizza
    {
        [Required(ErrorMessage = "Please enter the id of the pizza.")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter the name of the pizza.")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "The pizza name must be between 5 and 50 characters.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter the image URL of the pizza.")]
        public string Image { get; set; }

        [Required(ErrorMessage = "Please enter a description of the pizza.")]
        [MinWords(5, ErrorMessage = "The description must contain at least 5 words.")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Please enter the price of the pizza.")]
        [Range(1, 100, ErrorMessage = "The price must be between 1 and 100.")]
        public double Price { get; set; }

        public bool IsNew { get; set; }

    }

    public class MinWordsAttribute : ValidationAttribute
    {
        public MinWordsAttribute(int minWords)
        {
            MinWords = minWords;
        }

        public int MinWords { get; }

        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            if (value is string str && str.Split(' ').Length < MinWords)
            {
                return new ValidationResult(ErrorMessage);
            }

            return ValidationResult.Success;
        }
    }
}

la-mia-pizzeria-static/Controllers/PizzaController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {
        public static List<Pizza> PizzaListings = new List<Pizza> {
            new Pizza {
                Id = 1,
                Name = "Chicken Alfredo Pizza",
                Image = "/img/Chicken Alfredo Pizza.png",
                Description = "Alfredo sauce, cooked chicken, sliced mushrooms, mozzarella cheese, and fresh parsley",
                Price = 13.10,
                IsNew = true
            },
            new Pizza {
                Id = 2,
                Name = "Mushroom Pizza",
                Image = "/img/Funghi.png",
                Description = "Tomato sauce, mozzarella cheese, Italian sausage, sliced mushrooms, and fresh oregano",
                Price = 10.24,
                IsNew = false
            },
            new Pizza {
                Id = 3,
                Name = "Ham Pizza",
                Image = "/img/Ham.png",
                Description = "Pepperoni Pizza: Tomato sauce, mozzarella cheese, sliced ham, and oregano.",
                Price = 12.14,
                IsNew = false
            },
            new Pizza {
                Id = 4,
                Name = "Margherita Pizza",
                Image = "/img/MargheritaPizza.png",
                Description = "San Marzano tomatoes, fresh mozzarella cheese, fresh basil leaves, extra-virgin olive oil, and salt",
                Price = 9.64,
                IsNew = false
            },
            new Pizza {
                Id = 5,
                Name = "Meat Lovers Pizza",
                Image = "/img/Meat.png",
                Description = "Tomato sauce, mozzarella cheese, Italian sausage, bacon, pepperoni, and ham",
                Price = 14.87,
                IsNew = true
            },
            new Pizza {
                Id = 6,
                Name = "Pesto Pizza",
                Image = "/img/Pesto.png",
                Description = "Pesto sauce, sliced tomatoes, mozzarella cheese, and sliced black olives",
                Price = 11.24,
                IsNew = true
            },
            new Pizza {
                Id = 7,
                Name = "Tuna Pizza",
                Image = "/img/Tuna.png",
                Description = "Olive oil, mozzarella cheese, ricotta cheese, garlic, and fresh parsley and tuna",
                Price = 10.64,
                IsNew = false
            },
            new Pizza {
                Id = 8,
                Name = "Veggie Pizza",
                Image = "/img/Veggie Pizza.png",
                Description = "Tomato sauce, mozzarella cheese, green bell pepper, red onion, sliced mushrooms, and sliced black olives",
                Price = 12.14,
                IsNew = false
            },
            new Pizza {
                Id = 9,
                Name = "Buffalo Chicken Pizza",
                Image = "/img/BuffaloChickenPizza.png",
                Description = "Buffalo sauce, cooked chicken, blue cheese, mozzarella cheese, and sliced celery",
                Price = 13.44,
                IsNew = true
            }
        };

        public IActionResult Details(int id)
        {
            var pizza = PizzaListings.FirstOrDefault(l => l.Id == id);

            if (id < 1 || id > PizzaListings.Count)
            {
                return View("Error404");
            }
            return View(pizza);
        }

        public IActionResult Index()
        {
            return View(PizzaListings);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Pizza pizza)
        {
            if (!ModelState.IsValid)
            {
                return View(pizza);
            }

            pizza.Id = PizzaListings.Max(p => p.Id) + 1;
            PizzaListings.Add(pizza);

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Pizza pizza = PizzaListings.FirstOrDefault(p => p.Id == id);

            if (pizza == null)
            {
                return NotFound();
            }

            return View(pizza);
        }

        [HttpPost]
        public IActionResult Update(int id, Pizza data)
        {

            if (!ModelState.IsValid)
                return View("Edit", data);

            Pizza pizzaEdit = PizzaListings.Where(p => p.Id == id).FirstOrDefault();

            if (pizzaEdit != null)
            {
                pizzaEdit.Name = data.Name;
                pizzaEdit.Description = data.Description;
                pizzaEdit.Price = data.Price;
                pizzaEdit.Image = data.Image;

                PizzaListings.Add(data);
                return RedirectToAction("Index");
            }
            else
                return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            Pizza pizzaDelete = PizzaListings.Where(p => p.Id == id).FirstOrDefault();

            if (pizzaDelete != null)
            {
                PizzaListings.Remove(pizzaDelete);
                return RedirectToAction("Index", new { message = "Pizza eliminated successfully!" });
            }
            else
                return NotFound();
        }
    }
}

la-mia-pizzeria-static/Views/Pizza/Create.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Add a new pizza";
    @model Pizza
}

<h1 class="text-center text-xl">Add a new pizza</h1>
<div class="flex items-center justify-center p-12 max-w-screen-xl mx-auto">
    <div class="mx-auto w-full max-w-[550px]">
        <form method="post" asp-controller="pizza" asp-action="create">
            @Html.AntiForgeryToken()
            <div class="mb-5">
                <label for="Name"
                       class="mb-3 block text-base font-medium ">
                    Name
                </label>
                <input asp-for="Name"
                       placeholder="Name"
                       class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium outline-none focus:border-[#6A64F1] focus:shadow-md" />
                <span asp-validation-for="Name" class="text-red-500"></span>
            </div>
            <div class="mb-5">
                <label for="subject"
                       class="mb-3 block text-base font-medium ">
                    Image
                </label>
                <input asp-for="Image"
                       placeholder="Image"
                       class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium outline-none focus:border-[#6A64F1] focus:shadow-md" />
                <span asp-validation-for="Image" class="text-red-500"></span>
            </div>
            <div class="mb-5">
                <label for="Price"
                       class="mb-3 block text-base font-medium ">
                    Price
                </label>
                <input asp-for="Price"
                       placeholder="Price"
                       class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium outline-none focus:border-[#6A64F1] focus:shadow-md" />
                <span asp-validation-for="Price" class="text-red-500"></span>
            </div>
            <div class="mb-5">
                <label for="Description"
                       class="mb-3 block text-base font-medium ">
                    Description
                </label>
                <input asp-for="Description"
                       placeholder="Description"
                       class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium outline-none focus:border-[#6A64F1] focus:shadow-md" />
                <span asp-validation-for="Description" class="text-red-500"></span>
            </div>
            <div class="mb-5">
                <label for="subject"
                       class="mb-3 block text-base font-medium ">
                    IsNew
                </label>
                <input asp-for="IsNew"
                       placeholder="IsNew"
                       class="rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium outline-none focus:border-[#6A64F1] focus:shadow-md" />
                <span asp-validation-for="IsNew" class="text-red-500"></span>
            </div>
            <div>
                <button class="btn-primary rounded-md py-3 px-8 text-base font-semibold text-white outline-none">
                    Submit
                </button>
            </div>
        </form>
    </div>
</div>

la-mia-pizzeria-static/Views/Pizza/Details.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Product details";
    @model Pizza
}

<div class="min-w-screen py-24 flex items-center overflow-hidden relative">
    <div class="w-full max-w-6xl rounded mx-auto relative md:text-left">
        <div class="md:flex items-center -mx-10">
            <div class="w-full md:w-1/2 px-10 mb-10 md:mb-0">
                <div class="relative">
                    <img src="@Model.Image" class="w-full relative z-10" alt="@Model.Name">
                    <div class="border-4 absolute top-10 bottom-10 left-10 right-10 z-0"></div>
                </div>
            </div>
            <div class="w-full md:w-1/2 px-10">
                <div class="mb-10">
                    <h1 class="font-bold uppercase text-2xl mb-5">@Model.Name</h1>
                    <p class="text-lg">@Model.Description</p>
                </div>
                <div>
                    <div class="inline-block align-bottom mr-5">
                        <span class="font-bold text-5xl leading-none align-baseline">$@Model.Price</span>
                    </div>
                    <div class="inline-block align-bottom flex mt-5 gap-5">

                        <a href="@Url.Action("edit", "pizza", new { id = Model.Id })" class="btn btn-primary hover:opacity-100 rounded-full px-10 py-2 font-bold">Edit</a>

                        <form method="post" action="@Url.Action("Delete", "Pizza", new { id = Model.Id })">
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-primary hover:opacity-100 rounded-full px-10 py-2 font-bold">Delete</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

la-mia-pizzeria-static/Views/Pizza/Edit.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Add a new pizza";
    @model Pizza

}

<h1 class="text-center text-xl">Add a new pizza</h1>
<div class="flex items-center justify-center p-12 max-w-screen-xl mx-auto">
    <div class="mx-auto w-full max-w-[550px]">
        <form method="post" asp-action="Update" asp-route-id="@Model.Id">
            @Html.AntiForgeryToken()
            <div class="mb-5">
                <label for="Name"
                       class="mb-3 block text-base font-medium ">
                    Name
                </label>
                <input asp-for="Name"
                       placeholder="Name"
                       class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium outline-none focus:border-[#6A64F1] focus:shadow-md" />
                <span asp-validation-for="Name" class="text-red-500"></span>
            </div>
            <div class="mb-5">
                <label for="subject"
                       class="mb-3 block text-base font-medium ">
                    Image
                </label>
                <input asp-for="Image"
                       placeholder="Image"
                       class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium outline-none focus:border-[#6A64F1] focus:shadow-md" />
                <span asp-validation-for="Image" class="text-red-500"></span>
            </div>
            <div class="mb-5">
                <label for="Price"
                       class="mb-3 block text-base font-medium ">
                    Price
                </label>
                <input asp-for="Price"
                       placeholder="Price"
                       class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium outline-none focus:border-[#6A64F1] focus:shadow-md" />
                <span asp-validation-for="Price" class="text-red-500"></span>
            </div>
            <div class="mb-5">
                <label for="Description"
                       class="mb-3 block text-base font-medium ">
                    Description
                </label>
                <input asp-for="Description"
                       placeholder="Description"
                       class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium outline-none focus:border-[#6A64F1] focus:shadow-md" />
                <span asp-validation-for="Description" class="text-red-500"></span>
            </div>
            <div class="mb-5">
                <label for="subject"
                       class="mb-3 block text-base font-medium ">
                    IsNew
                </label>
                <input asp-for="IsNew"
                       placeholder="IsNew"
                       class="rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium outline-none focus:border-[#6A64F1] focus:shadow-md" />
                <span asp-validation-for="IsNew" class="text-red-500"></span>
            </div>
            <div>
                <button type="submit" class="btn btn-primary hover:opacity-100 rounded-full px-10 py-2 font-bold">Update</button>
            </div>
        </form>
    </div>
</div>

la-mia-pizzeria-static/Views/Pizza/Index.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Bringing a slice of happiness to your doorstep";
    @model List<Pizza>
}

@section _Jumbotron {
    @await Html.PartialAsync("_PizzaJumbotron")
}


<!-- Menu Section -->
<div class="max-w-screen-xl mx-auto">
    <div class="flex justify-between my-4">
        <h1 class="font-bold text-6xl">Menu</h1>
        <a class="btn-primary btn text-white font-bold py-2 px-4 rounded" href="@Url.Action("create", "pizza")"> Create New Pizza Listing</a>
    </div>


    <!-- Listings -->
    <div class="grid-cols-3	grid">

        @foreach (Pizza listing in Model)
        {
            <div class="card w-96 bg-base-100 shadow-xl">
                <figure><img src="@listing.Image" /></figure>
                <div class="card-body">
                    <h2 class="card-title">
                        @listing.Name
                        @if (listing.IsNew)
                        {
                            <span class="badge badge-secondary">NEW</span>
                        }
                    </h2>
                    <p>@listing.Description</p>
                    <div class="card-actions items-center justify-between">
                        <span class="font-bold text-2xl">$@listing.Price</span>
                        <a href="@Url.Action("details", "pizza", new { id = listing.Id })" class="btn btn-primary">Order Now</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

la-mia-pizzeria-static/Views/Pizza/_PizzaJumbotron.cshtml
<!-- Jumbotron -->
<div class="hero">
    <div class="hero-content flex-col lg:flex-row-reverse">
        <img src="/img/hero-slice.png" class="max-w-md" />
        <div>
            <h1 class="text-5xl font-bold">Satisfy Your Thirst with our Delicious Sodas!</h1>
            <p class="py-6 w-4/5 text-lg">Whether you prefer classic flavors like cola or you're feeling adventurous with our gourmet options, we've got you covered. Sit back, relax, and enjoy the refreshing taste of our delicious sodas right from the comfort of your home. Order now and experience a sip of heaven with every gulp.</p>
        </div>
    </div>
</div>